### ISSUE TITLE
gas price check can be overridden by calling buyDuelTokens() instead of fallback function

### ISSUE THREAD

**Issue by io4** [dueltoken/token#1]

**Comment by dueltoken** [comment]
This is a valid concern, fixed in [53163cb](https://github.com/dueltoken/token/commit/53163cb54435fc3594a5d3fdc9710b681604b67d)

Thanks for reporting this bug, you will be rewarded with 10000 DUEL at the end of the ICO.
In order to receive the DUEL, comment here with the address of an ERC20 compliant wallet.

Many thanks!

**Comment by io4** [comment]
Address is 0x9FCfE63108f0957aAD1C6F2eD30270e8D35C6491 for both #4 and #1
