### ISSUE TITLE
Three bugs

### ISSUE THREAD

**Issue by samczsun** [dueltoken/token#2]
1) The softcap is set to 0.5eth in the contract, but the website says the softcap is 2000eth

2) Coins can be purchased after ICO
This is because after the ICO, `getCurrentPhase() = Ended` but `buyDuelTokens` only checks for `getCurrentPhase() = Closed`

3) Coins can be purchased for free under certain conditions
If:
* The softcap has not been reached
* The ICO has ended
* There are still more tokens to purchase

Then
* `getCurrentPhase() = Ended`
* `softCapReached() = False`
* `tokensRemaining > 0`

By exploiting (2), an attacker can repeatedly call `buyDuelTokens` and `refund`

**Comment by io4** [comment]
How can you get tokens for free if there's a base price? calculateAmountOfBaseTokensForWeiValue() only adds to the value that can become 0 (the bonus).

Also Closed phase is only reachable before the crowdsale is setup because once the timeframe ends, Ended gets locked-in forever. (now > end).

Just my opinion, I am not a duel token team member.

**Comment by dueltoken** [comment]
Thanks for taking the time to look into this.

1:  Is indeed wrong, this value comes from the testing phase. You will receive 10000 DUEL for this one.

2+3: This is indeed a scenario where one would be able to buy 'free' tokens if the softcap isn't reached after the end date. However this doesn't impact the flow of our ICO as the project won't be continued in this case and the token's will hold no value (they will never be made tradable). However, the bug you actually found is that it is indeed possible to buy tokens when the ICO ended and the softcap is reached. This is not intended and therefor you will also receive 10000 DUEL.

Both issues are fixed in [a83dbee](https://github.com/dueltoken/token/commit/a83dbee88f64dd2bc218666fcbb4be6e20328cf5)

Thanks for reporting these bugs, you will be rewarded with 20000 DUEL at the end of the ICO.
In order to receive the DUEL, comment here with the address of an ERC20 compliant wallet.

Many thanks!

**Comment by samczsun** [comment]
Thanks. Here's my wallet: 0xFb8F506D6998E132F49276d83727dfE8298bBEcC
