### ISSUE TITLE
The crowdsale contract owns the token contract, that means that pausable function is useless because only crowdsale can call it

### ISSUE THREAD

**Issue by io4** [dueltoken/token#4]

**Comment by dueltoken** [comment]
Again a valid concern, this was a last minute update to switch ownership around, we made a delegate function for tradable, but not for pausable.

You will also get 10000 DUEL for this one.

This issue is fixed in [aab07d6](https://github.com/dueltoken/token/commit/aab07d6148af3e2f7f39992c6ed037f3850871d6)

Thanks so much for taking the time to go trough the contract. You will be added to the bounty list once we receive your ETH address.

**Comment by io4** [comment]
Address given in #1 thread
